### ISSUE TITLE
TypeError when trying to compile templates

### ISSUE THREAD

**Issue by vamsiampolu** [mattacular/grunt-handlebars-compiler#17]
I am using this configuration when trying to compile the templates:

```
handlebars:{
    all:{
        files:{
            "js/partials.js":"templates/source/**/*.handlebars"
        },
        options:{
             namespace: 'Handlebars.templates'
        }
    }
}
```

`When I run`grunt handlebars` I get this error:

```
TypeError: _(...).map(...).flatten is not a function
    at Object.module.exports [as findup] (C:\Users\mySAP\Desktop\workspace\maperp_mobile_demo\www\node_modules\findup-sync\lib\findup-sync.js:33:8)
    at Task.task.init (C:\Users\mySAP\Desktop\workspace\maperp_mobile_demo\www\node_modules\grunt\lib\grunt\task.js:427:16)
    at Object.grunt.tasks (C:\Users\mySAP\Desktop\workspace\maperp_mobile_demo\www\node_modules\grunt\lib\grunt.js:120:8)
    at Object.module.exports [as cli] (C:\Users\mySAP\Desktop\workspace\maperp_mobile_demo\www\node_modules\grunt\lib\grunt\cli.js:38:9)
    at Object.<anonymous> (C:\Users\mySAP\AppData\Roaming\npm\node_modules\grunt-cli\bin\grunt:45:20)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
```

**Comment by nicosavini** [comment]
How did you solve this issue? It's happening to me in another project? Thanks,

**Comment by mattacular** [comment]
Can you paste your Grunt task here which is causing the issue?
